### ISSUE TITLE
Add an "About Page"

### ISSUE THREAD

**Issue by AkhilaSunesh** [prathamjagga/automarket#34]
**Is your feature request related to a problem? Please describe.**
Its not easy to understand the features of this project.

**Describe the solution you'd like**
Adding an "About page" would help resolve the issue

**Additional context**
Kindly assign this issue to me

**Comment by knight1001d** [comment]
cd face
npm i
npm run dev

above steps will open the about application.

**Comment by AkhilaSunesh** [comment]
It's not visible within the website

**Comment by knight1001d** [comment]
hi @AkhilaSunesh , sorry for responding lately.
You can go ahead if you wanna work on this. Let me know if I should assign you.

**Comment by AkhilaSunesh** [comment]
yes please assign this to me

**Comment by prathamjagga** [comment]
assigned to you, @AkhilaSunesh

**Comment by prathamjagga** [comment]
stale.
